package application.controller;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

import javafx.scene.layout.AnchorPane;

public class PrincipalController {
	@FXML
	private AnchorPane taListaLivros;
	@FXML
	private Button buscaLivro;
	@FXML
	private Button copiaLivro;
	@FXML
	private Button inserirLivro;
	@FXML
	private Button attLivro;
	@FXML
	private Button delLivro;
	@FXML
	private Button listarLivro;

	// Event Listener on Button[#buscaLivro].onAction
	@FXML
	public void buscaLivro(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#copiaLivro].onAction
	@FXML
	public void copiaLivro(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#inserirLivro].onAction
	@FXML
	public void acaoLivro(ActionEvent event) {
		// TODO Autogenerated
	}
}
